# Generated by Django 5.2.3 on 2025-11-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telles", "0002_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
