# Generated by Django 4.0 on 2025-11-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telles', '0004_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', '出席'), ('absent', '欠席'), ('late', '遅刻'), ('leave', '早退')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
