# Generated by Django 5.2.7 on 2025-11-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telles', '0005_alter_attendance_options_alter_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', '欠席'), ('late', '遅刻'), ('leave', '早退')], max_length=20),
        ),
    ]
