# Generated by Django 5.2.3 on 2025-11-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telles", "0006_alter_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
