# Generated by Django 5.2.7 on 2025-11-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telles', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
