# Generated by Django 5.2.3 on 2025-11-20 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telles", "0007_attendance_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
