# Generated by Django 5.2.3 on 2025-11-21 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telles", "0008_attendance_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
