# Generated by Django 3.2 on 2025-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telles', '0009_alter_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('department', 'class_name')},
            },
        ),
    ]
