# Generated by Django 5.2.3 on 2026-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telles", "0010_auto_20251125_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
